### ISSUE TITLE
안녕하세요! 저도 같이 기여할 수 있을까요?

### ISSUE THREAD

**Issue by keon** [LeeTaewoo/torch_kor_manual#1]
토치를 배우는중인데 같이 다큐먼테이션을 발전시켜나가도 될까요??

블로그에서 강좌도 같이 하시는것 같은데 도움이 많이 될 것 같습니다! 감사합니다!

**Comment by LeeTaewoo** [comment]
물론입니다. 참여해 주셔서 '정말' 고맙습니다. :)

필요한 일들을 정리해 보았습니다:
    1. torch7 번역된 문서(구글 doc 포맷)를 *.md 포맷으로 바꾸기. -> torch7/ PR.
https://docs.google.com/document/d/1TUukRpBV_9HKZOvczUTzHxS-S8iag5utaPdlGXBXs0U/edit#
    2. nn/table.md 번역 (완료)
    3. nn/training.md 번역
    4. zbs-torch/README-zbs.md 번역
    5. 이미 번역된 문서에 대한 교정(proofreading)
    6. nngraph 패키지 문서 번역

**Comment by LeeTaewoo** [comment]
제가 기트허브 사용법을 잘 모릅니다. 공동 작업을 위해, 혹시 제가 기트허브에서 해야할 일이 있으면 말씀해주십시오. :)
